### ISSUE TITLE
The codebase is too disorganized !!!

### ISSUE THREAD

**Issue by abhijeetmanhas** [STAC-IITMandi/Exoplanet-Hunt#8]
It need to packaged, and all files should be transformed to functions and classes.

**Comment by LalitNM** [comment]
@abhijeetmanhas if we want to make a python library, why we are not starting from a template?
In my opinion that would be good.

**Comment by abhijeetmanhas** [comment]
We will use open astronomy basic template, which many packages use

**Comment by abhijeetmanhas** [comment]
Oh, hackdays are over, this thing is finished by EOD.

**Comment by shreyasbapat** [comment]
I think a person should not have rights to the packages in club namespace.

**Comment by abhijeetmanhas** [comment]
Thanks Shreyas for informing,
I have changed everything in license, I have to change that in author as well.
